<a href="https://colab.research.google.com/github/amroth917/IST652/blob/master/Roth_Allison_HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Allison Roth
July 25, 2019
Lab 2
IST652

In [0]:
# Set wd in Google CoLab
from google.colab import drive
drive.mount('/content/drive')
#Import Packages
import pandas as pd
import numpy as np
import decimal
from decimal import *

Data cleaning - removing unneeded columns and reducing the rows from 40,000 to 4,000

In [14]:
#Importing CSV as a Pandas Dataset
bf = pd.read_csv("//BlackFriday_smaller.csv")

      User_ID Product_ID Gender  ... Marital_Status  Product_Category_1 Purchase
0     1000001  P00069042      F  ...              0                   3     8370
1     1000001  P00248942      F  ...              0                   1    15200
2     1000001  P00087842      F  ...              0                  12     1422
3     1000001  P00085442      F  ...              0                  12     1057
4     1000002  P00285442      M  ...              0                   8     7969
5     1000003  P00193542      M  ...              0                   1    15227
6     1000004  P00184942      M  ...              1                   1    19215
7     1000004  P00346142      M  ...              1                   1    15854
8     1000004   P0097242      M  ...              1                   1    15686
9     1000005  P00274942      M  ...              1                   8     7871
10    1000005  P00251242      M  ...              1                   5     5254
11    1000005  P00014542      M  ...              1                   8     3957
12    1000005  P00031342      M  ...              1                   8     6073
13    1000005  P00145042      M  ...              1                   1    15665
14    1000006  P00231342      F  ...              0                   5     5378
15    1000006  P00190242      F  ...              0                   4     2079
16    1000006   P0096642      F  ...              0                   2    13055
17    1000006  P00058442      F  ...              0                   5     8851
18    1000007  P00036842      M  ...              1                   1    11788
19    1000008  P00249542      M  ...              1                   1    19614
20    1000008  P00220442      M  ...              1                   5     8584
21    1000008  P00156442      M  ...              1                   8     9872
22    1000008  P00213742      M  ...              1                   8     9743
23    1000008  P00214442      M  ...              1                   8     5982
24    1000008  P00303442      M  ...              1                   1    11927
25    1000009  P00135742      M  ...              0                   6    16662
26    1000009  P00039942      M  ...              0                   8     5887
27    1000009  P00161442      M  ...              0                   5     6973
28    1000009  P00078742      M  ...              0                   5     5391
29    1000010  P00085942      F  ...              1                   2    16352
...       ...        ...    ...  ...            ...                 ...      ...
3969  1000654  P00193542      M  ...              1                   1    11424
3970  1000654  P00282642      M  ...              1                   5     6884
3971  1000654  P00288342      M  ...              1                   8     8138
3972  1000654  P00153842      M  ...              1                   8     6060
3973  1000654  P00228242      M  ...              1                   8     7943
3974  1000654  P00354942      M  ...              1                   8     6036
3975  1000655  P00335942      F  ...              0                   8     6170
3976  1000655  P00209842      F  ...              0                   5     7185
3977  1000655  P00314942      F  ...              0                   8     6184
3978  1000655  P00323942      F  ...              0                   8     6035
3979  1000655  P00347042      F  ...              0                   8     3993
3980  1000655  P00328642      F  ...              0                   8     3915
3981  1000655  P00239342      F  ...              0                   8     5903
3982  1000655  P00085042      F  ...              0                   5     5179
3983  1000655  P00022942      F  ...              0                   5     3444
3984  1000655  P00212742      F  ...              0                   5     1753
3985  1000655  P00108842      F  ...              0                   5     5262
3986  1000655  P00029742      F  ...              0                   5     3435
3987  1000655  P00190742      F  ...              0                   3     8214
3988  1000655  P00195342      F  ...              0                   2     3710
3989  1000656  P00331542      F  ...              1                   5     6878
3990  1000656  P00116742      F  ...              1                  11     5981
3991  1000656  P00342742      F  ...              1                   8     5920
3992  1000656  P00120142      F  ...              1                   5     8663
3993  1000657  P00238442      F  ...              0                   6    20181
3994  1000657  P00139542      F  ...              0                   5     6921
3995  1000657  P00328042      F  ...              0                   8     8028
3996  1000657  P00004342      F  ...              0                   8     8088
3997  1000658  P00033942      F  ...              0                   5     5243
3998  1000659  P00114142      F  ...              0                   8     5931

[3999 rows x 10 columns]

In [118]:
#Question 1
#Which customer has the largest purchase on black friday? What's their gender and age?

#bf['Gender'].value_counts()
#bf['Purchase'].max()
#bf['Age'].value_counts()

bfmax = bf.loc[bf['Purchase'].idxmax()]

print("The customer with the largest purchase on Black Friday is", bfmax[2],"and",bfmax[3], 
      ", spending a total of ${:,.2f}".format(bfmax[9]))

bf.to_csv(r'Path where you want to store the exported CSV file\File Name.csv')

bfmax_export = bfmax.to_csv (r'//BlackFridayMaxPurchase.csv', index= None, header=True)

The customer with the largest purchase on Black Friday is M and 26-35 , spending a total of $23,826.00

In [119]:
#Question 2
#What was the average purchase within each age group?

#df2 = {n: rows[1] for n, rows in enumerate(bf.groupby('Gender'))}
#print(df2[1])

bfage = bf.groupby(['Age'], as_index=False).mean().groupby('Age').mean()

#print("On average, people within", bfage.index[0],"age group spent:",bfage['Purchase'][0])

count = 0
for line in bfage:
    print ("On average, people within", bfage.index[count],"age group spent ${:,.2f} on Black Friday.".format(bfage['Purchase'][count]))
    count += 1
    
    
bfage_export = bfage.to_csv (r'//BlackFridayAgeAvg.csv', index= None, header=True)

On average, people within 0-17 age group spent $9,036.14 on Black Friday.
On average, people within 18-25 age group spent $9,265.96 on Black Friday.
On average, people within 26-35 age group spent $9,495.87 on Black Friday.
On average, people within 36-45 age group spent $9,692.95 on Black Friday.
On average, people within 46-50 age group spent $9,379.29 on Black Friday.